import {Clothes} from "@/scripts/types";

const clothes: Clothes[] = [
    {
        name: 'Boa 1" Elite split shorts',
        price: 42,
        rating: 5,
        img: "/images/clothes/Boa-shorts.png",
        use: "Training/Racing",
        brand: "BOA",
        brandLogo: "/images/logos/boa-logo.png",
        link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
        brandLink: "https://www.nike.com/w?q=vaporfly&vst=vaporfly",
        review: "stuff",
        id: 'boa-elite-split-shorts',
        type: "clothes",
        clotheType: "shorts",
        features: [
            {
                name: "Inseam",
                value: "1\""
            },
            {
                name: "Patterns",
                value: "Yes"
            },
        ]
    },
    {
        name: "Nike Dri-FIT ADV AeroSwift",
        price: 90,
        rating: 4,
        img: "/images/clothes/aeroswiftSinglet2.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Mens_Nike_Vaporfly/catpage-MVAPORFLY.html",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nikr-dri-fit-adv-aeroswift',
        type: "clothes",
        clotheType: "singlet",

    },
//     BOA Men's Constrictor Plus Half Tight
    {
        name: "BOA Men's Constrictor Plus Half Tight",
        price: 44,
        rating: 4,
        img: "/images/clothes/boaConstrictorPlusHalfTight.png",
        use: "Training/Racing",
        brand: "BOA",
        brandLogo: "/images/logos/boa-logo.png",
        link: "https://www.runningwarehouse.com/BOA_Mens_Constrictor_Plus_Half_Tight/descpage-BMCPHT.html?color=bk",
        brandLink: "https://www.boafit.com/",
        review: "stuff",
        id: 'boa-mens-constrictor-plus-half-tight',
        type: "clothes",
        clotheType: "spandex",
    },
//     BOA Men's Singlet
    {
        name: "BOA Men's Singlet",
        price: 30,
        rating: 4,
        img: "/images/clothes/boaSinglet.png",
        use: "Training/Racing",
        brand: "BOA",
        brandLogo: "/images/logos/boa-logo.png",
        link: "https://www.runningwarehouse.com/BOA_Mens_Singlet_/descpage-BOAMSAL.html?color=rd",
        brandLink: "https://www.boafit.com/",
        review: "stuff",
        id: 'boa-mens-singlet',
        type: "clothes",
        clotheType: "singlet",
    },
//     Nike Men's Core Dri-FIT ADV Aeroswift Half Tight
    {
        name: "Nike Men's Core Dri-FIT ADV Aeroswift Half Tight",
        price: 90,
        rating: 5,
        img: "/images/clothes/aeroswift-half-tight.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Nike_Mens_Core_Dri-FIT_ADV_Aeroswift_Half_Tight_/descpage-NMCAWHT.html?color=bk",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nike-mens-core-dri-fit-adv-aeroswift-half-tight',
        type: "clothes",
        clotheType: "spandex",
    },
//     Nike Men's Dri-FIT ADV Aeroswift Tight
    {
            name: "Nike Men's Dri-FIT ADV Aeroswift Tight",
            price: 125,
            rating: 5,
            img: "/images/clothes/nikeAeroswiftTight.png",
            use: "Training/Racing",
            brand: "Nike",
            brandLogo: "/images/logos/nikeLogo.jfif",
            link: "https://www.runningwarehouse.com/Nike_Mens_Dri-FIT_ADV_Aeroswift_Tight_Black_White/descpage-NMCASTG.html?color=",
            brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
            review: "stuff",
            id: 'nike-mens-dri-fit-adv-aeroswift-tight',
            type: "clothes",
            clotheType: "tights",
    },
//     Nike Men's Fall 2" Aeroswift Short
    {
        name: "Nike Men's Fall 2\" Aeroswift Short",
        price: 80,
        rating: 4,
        img: "/images/clothes/nikeAeroswiftShort.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Nike_Mens_Fall_2_Aeroswift_Short/descpage-NMF2ASS.html?color=",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nike-mens-fall-2-aeroswift-short',
        type: "clothes",
        clotheType: "shorts",
    },
//     Nike Men's Core Dri-FIT Phenom Elite Woven Pant
    {
        name: "Nike Men's Core Dri-FIT Phenom Elite Woven Pant",
        price: 95,
        rating: 4,
        img: "/images/clothes/nikePhenomEliteWovenPant.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Nike_Mens_Core_Dri-FIT_Phenom_Elite_Woven_Pant/descpage-NMCPEWP.html?color=",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nike-mens-core-dri-fit-phenom-elite-woven-pant',
        type: "clothes",
        clotheType: "pants",
    },
//     Nike Men's Core Dri-FIT Phenom Elite Tight Black
    {
        name: "Nike Men's Core Dri-FIT Phenom Elite Tight Black",
        price: 80,
        rating: 4,
        img: "/images/clothes/nikePhenomEliteTight.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Nike_Mens_Core_Dri-FIT_Phenom_Elite_Tight/descpage-NMCPEHT.html?color=",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nike-mens-core-dri-fit-phenom-elite-tight-black',
        type: "clothes",
        clotheType: "tights",
    },
//     Nike Men's Core Dri-FIT Fast Half Tight
    {
        name: "Nike Men's Core Dri-FIT Fast Half Tight",
        price: 60,
        rating: 4,
        img: "/images/clothes/nikeFastHalfTight.png",
        use: "Training/Racing",
        brand: "Nike",
        brandLogo: "/images/logos/nikeLogo.jfif",
        link: "https://www.runningwarehouse.com/Nike_Mens_Core_Dri-FIT_Fast_Half_Tight/descpage-NMCFHT.html?color=",
        brandLink: "https://www.nike.com/t/dri-fit-adv-aeroswift-mens-racing-singlet-9xgk0c",
        review: "stuff",
        id: 'nike-mens-core-dri-fit-fast-half-tight',
        type: "clothes",
        clotheType: "spandex",
    },


]
export {clothes};